source: src
destination: build
documentation_assets: doc_assets
custom_markdown: doc_assets/CortanaMarkdownRenderer.rb
index: README
css_include:
  - '/css/interexchange.css'
js_include:
  - '/js/vendors.js'
  - '/js/interexchange.js'
name_scope: ' - '
