source: src
destination: build
documentation_assets: layout
custom_markdown: layout/CortanaMarkdownRenderer.rb
index: README
css_include:
  - '/css/interexchange.css'
js_include:
  - '/js/vendors.js'
  - '/js/interexchange.js'
name_scope: ' - '
